feat: deprecate Mumbai testnet (#3521)
### Description

- Removes all reference to Mumbai testnet, since it is soon being
[deprecated](https://polygon.technology/blog/polygon-pos-is-cooking-the-napoli-upgrade-means-better-ux-the-mumbai-testnet-takes-a-bow)
by the Polygon team
- Monorepo docker tag:
https://console.cloud.google.com/gcr/images/abacus-labs-dev/global/hyperlane-monorepo@sha256:d4b44359cae9c4e3bdeb6f965c59d056f7fce72c42069adc0dea038ac600785a/details?authuser=5&project=abacus-labs-dev&tab=info
- Agent docker tag:
https://console.cloud.google.com/gcr/images/abacus-labs-dev/global/hyperlane-agent@sha256:a578d96f7f06721d0b6cd8095d6a1fa5d22f01b59eba3320ee3b1fe34ca3c5df/details?authuser=5&project=abacus-labs-dev&tab=info

### Drive-by changes

- Adds missing Testnet domains, Fuji & BSC Testnet
  - Fix for failing `test-rs` CI check with
```
error[E0004]: non-exhaustive patterns: `chain::KnownHyperlaneDomain::Fuji` and `chain::KnownHyperlaneDomain::BinanceSmartChainTestnet` not covered
   --> hyperlane-core/src/utils.rs:226:15
    |
226 |           match $v {
    |                 ^^ patterns `chain::KnownHyperlaneDomain::Fuji` and `chain::KnownHyperlaneDomain::BinanceSmartChainTestnet` not covered
```

### Related issues
- Dependency on #3523 
- Fixes #1181 

### Backward compatibility

- [x] Backwards compatible
- [x] Requires docker image tags to be added post-build
- [x] Requires agent artifact cleanup in cloud account:
https://www.notion.so/hyperlanexyz/Runbook-83c755f2652943289cf98cd1309487a8?pvs=4#77730653a12f409dacfbd427cab545d3

### Testing

* Build success
* `yarn hyperlane chains list -e testnet` does not return `mumbai`
* fork.sh script success locally