feat: chunk message db insertions (#6114)
### Description

Instead of inserting all the messages we receive in a single db
transaction, we chunk it into smaller sizes.
This prevents us from running into `Too many arguments` errors from
Postgres for exceeding their `u16::MAX` parameter count.

### Related issues
- fixes
https://linear.app/hyperlane-xyz/issue/ENG-1390/scraper-cannot-insert-too-many-records

### Backward compatibility

Yes

### Testing

Manual. From Jeff:

Tried it locally with a postgres instance with 100k messages and it
failed without chunking
```
running 1 test
RES: Err(Query Error: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 1000000 (sqlx_postgres::connection::executor:215)

Caused by:
   0: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 1000000 (sqlx_postgres::connection::executor:215)
   1: encountered unexpected or invalid data: PgConnection::run(): too many arguments for query: 1000000 (sqlx_postgres::connection::executor:215)

Location:
    agents/scraper/src/db/message.rs:320:9)
test db::message::tests::test_store_dispatched_messages_real_postgres ... ok
```

Tried it again with chunking + transaction and it didn't have any errors
:+1:
So we can use the transaction if we want the action to be atomic, but
the important part is the chunking.